service: serverless-todo-api

plugins:
  - serverless-offline
  - serverless-dynamodb-local

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-northeast-1
  stage: ${env:DEPLOY_STAGE}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:ap-northeast-1:*:*'
  environment:
    DEPLOY_STAGE: ${env:DEPLOY_STAGE}
    TODOS_TABLE_NAME: ${env:DEPLOY_STAGE}_Todo

package:
  exclude:
    - .git/**
    - .nyc_output/**
    - coverage/**
    - .idea/**
    - src/**
    - config/**

custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migration: true
    migration:
      dir: ./config/migrations

functions:
  createTodo:
    handler: build/functions/todo.create
    events:
      - http:
          path: todo
          method: post
          cors: true
  findTodo:
    handler: build/functions/todo.find
    events:
      - http:
          path: todo/{id}
          method: get
          cors: true
  findTodoList:
    handler: build/functions/todo.findList
    events:
      - http:
          path: todo
          method: get
          cors: true
  updateTodo:
    handler: build/functions/todo.update
    events:
      - http:
          path: todo/{id}
          method: put
          cors: true
  deleteTodo:
    handler: build/functions/todo.deleteTodo
    events:
      - http:
          path: todo/{id}
          method: delete
          cors: true

resources:
  Resources:
    ResourcesDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${env:DEPLOY_STAGE}_Todo
