service: serverless-todo-api

plugins:
  - serverless-offline
  - serverless-dynamodb-local

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  stage: ${env:DEPLOY_STAGE}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:us-east-1:*:*'
  environment:
    DEPLOY_STAGE: ${env:DEPLOY_STAGE}
    TODOS_TABLE_NAME: ${env:DEPLOY_STAGE}_Todo

package:
  exclude:
    - .git/**
    - .nyc_output/**
    - coverage/**
    - .idea/**
    - src/**
    - config/**
    - node_modules/aws-sdk/**
    - node_modules/.bin/**
    - node_modules/.cache/**
    - node_modules/@types/**
    - node_modules/mocha/**
    - node_modules/power-assert/**
    - node_modules/node-inspector/**
    - node_modules/serverless/**
    - node_modules/serverless-dynamodb-local/**
    - node_modules/serverless-offline/**
    - node_modules/ts-loader/**
    - node_modules/ts-node/**
    - node_modules/tslint/**
    - node_modules/typescript/**

custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migration: true
    migration:
      dir: ./config/migrations

functions:
  createTodo:
    handler: build/functions/todo.create
    events:
      - http:
          path: todo
          method: post
          cors: true
  findTodo:
    handler: build/functions/todo.find
    events:
      - http:
          path: todo/{id}
          method: get
          cors: true
  findTodoList:
    handler: build/functions/todo.findList
    events:
      - http:
          path: todo
          method: get
          cors: true

resources:
  Resources:
    ResourcesDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${env:DEPLOY_STAGE}_Todo
